# Generated by Django 5.2 on 2025-04-16 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_discount_discount_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountusage',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='discountusage',
            unique_together={('user', 'discount', 'date')},
        ),
    ]
